python main.py \
        --mode train \
        --data_name kamed \
        --data_type train \
        --evaluate_during_training \
        --per_gpu_train_batch_size 4 \
        --output_dir ./train \
        --act_entity_dir ../results/df_results/kamed \
        --lr 2e-5 \
        --num_train_epochs 10 \
        --k_entity 10 \
        --train_name demo_kamed \
